# Generated by Django 4.1.1 on 2022-11-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_id"),
    ]

    operations = [
        migrations.RenameField(model_name="product", old_name="id", new_name="P_id",),
    ]
